name: yesod-fast-devel
version: '0.1.1.0'
synopsis: Fast live-reloading for yesod applications.
category: Development
author: Arne Link, Pedro Tacla Yamada
maintainer: tacla.yamada@gmail.com
license: BSD3

default-extensions:
- OverloadedStrings
- LambdaCase

ghc-options:
- -O2
- -threaded

dependencies:
- Glob >=0.7
- ansi-terminal
- base >=4.7 && <5
- bytestring >=0.10.6.0
- directory >=1.2.2.0
- filepath >=1.4.0.0
- fsnotify >=0.1.0.0
- optparse-applicative
- process >=1.2.0.0
- pureMD5 >=2.1
- stm >=2.1.1.0
- system-filepath
- temporary >=1.2.0.0
- text >=1.2.0.0

executables:
  yesod-fast-devel:
    main: Main.hs

data-files:
- PatchedDevelMain.hs
- OriginalDevelMain.hs

tested-with: ghc >=7.6
