flags:
  text:
    integer-simple: false
  semigroups:
    bytestring-builder: false
packages:
- '.'
extra-deps:
- Glob-0.7.5
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- async-2.0.2
- cereal-0.5.1.0
- crypto-api-0.13.2
- dlist-0.7.1.2
- entropy-0.3.7
- exceptions-0.8.0.2
- fsnotify-0.2.1
- hashable-1.2.6.0
- hfsevents-0.1.6
- mtl-2.2.1
- optparse-applicative-0.13.2.0
- pureMD5-2.1.2.1
- semigroups-0.18.2
- stm-2.4.4
- system-filepath-0.4.13.4
- tagged-0.8.2
- temporary-1.2.0.3
- text-1.2.1.3
- transformers-compat-0.4.0.4
- unix-compat-0.4.1.4
- unordered-containers-0.2.8.0
resolver: ghc-7.10
